import sqlite3 as lite

con = lite.connect('formu.db')

with con:
    cur=con.cursor()
    cur.execute("CREATE TABLE formulario(ID INTEGER PRIMARY KEY AUTOINCREMENT , DTREGISTRO NUMERIC NOT NULL, NUMBONUS NUMERIC NOT NULL, DTENTRADA DATE NOT NULL, NUMNOTAENT NUMERIC NOT NULL, NUMLOTE NUMERIC NOT NULL, CODPROD NUMERIC NOT NULL, FABRICANTE TEXT NOT NULL, DTFABRICACAO DATE NOT NULL, DTVALIDADE DATE NOT NULL, QT NUMERIC NOT NULL)  ")